# Generated by Django 6.0.5 on 2026-05-17 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(unique=True)),
                ("capacidad", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("ocupado", "Ocupado"),
                            ("reservado", "Reservado"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente_nombre", models.CharField(max_length=100)),
                ("cliente_telefono", models.CharField(max_length=20)),
                ("fecha_hora", models.DateTimeField()),
                ("personas", models.PositiveIntegerField()),
                ("confirmada", models.BooleanField(default=False)),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="mesas.mesa",
                    ),
                ),
            ],
        ),
    ]
